title: SSE Conference Deadlines
description: Countdowns to top conference deadlines.
author: Valentin Zieglmeier

domain: "deadlines.sse.in.tum.de"
baseurl: ""

twitter_username: hiddenmarkov
github_username: tum-i4
github_repo: deadlines
