title: Security and Privacy Conference Deadlines
description: Countdowns to top Security and Privacy conference deadlines.
author: Bogdan Kulynych

domain: "sec-deadlines.github.io"
baseurl: ""

twitter_username: hiddenmarkov
github_username: sec-deadlines
github_repo: sec-deadlines

markdown: kramdown

